os: Visual Studio 2019
build: off
environment:
  matrix:
    - platform: x86_64
      channel: stable
      target: x86_64-pc-windows-msvc

    - platform: i686
      channel: stable
      target: i686-pc-windows-msvc

    - platform: arm64
      channel: stable
      target: aarch64-pc-windows-msvc

    - platform: i586
      channel: stable
      target: i586-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

build_script:
  cargo build --release --target=%target%

artifacts:
  - path: target\$(target)\release\*.exe
    name: loudnessnorm-$(target)

# Exclude building on every single commit
# except if the code does change.
only_commits:
  files:
    - src\**\*
