image:
  - Visual Studio 2019
  - Visual Studio 2017

build: off
environment:
  matrix:
    - target: x86_64-pc-windows-msvc
    - target: i686-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

cache: ["%USERPROFILE%\.cargo\bin"]

build_script:
  cargo build --release --target=%target%

artifacts:
  - path: target\$(target)\release\*.exe
    name: loudnessnorm-$(target)

only_commits:
  files:
    - src\**\*
