[package]
name = "loudnessnorm"
description = "An RMS based audio Loudness Normalizer."
version = "1.1.2"
homepage = "https://github.com/nullvideo/loudnessnorm"
authors = ["nullvideo <bsantanu381@gmail.com>"]
license-file = "LICENSE"
edition = "2018"
exclude = ["target/**/*", "*.lock", "*.yml"]


[dependencies]
hound = "3.4.0"
structopt = "0.3"