[package]
name = "loudnessnorm"
description = "An RMS based audio loudness normalizer"
readme = "README.md"
homepage = "https://github.com/nullvideo/loudnessnorm"
version = "1.2.0"
authors = ["nullvideo <bsantanu381@gmail.com>"]
license-file = "LICENSE"
edition = "2018"
exclude = ["target/**/*", "*.lock", "*.yml"]

[dependencies]
hound = "3.4.0"
structopt = "0.3"